### ISSUE TITLE
Misaligned Dashboard

### ISSUE THREAD

**Issue by ShivanshPlays** [satyam8932/genieai#19]
![image](https://github.com/user-attachments/assets/951e3888-24c9-4c81-8fd8-bd78a1e71422)
I can fix the alignment issue in the dashboard, as you can see, the navbar has centered contents and the main page has left aligned components.
I can also work on making the cards look better (UI)

**Comment by satyam8932** [comment]
Hello @ShivanshPlays, ok so you can work on this issue but make sure that you have to write production grade code with proper comments,

Create your own branch in your fork repo and make the changes, attach them as image in the pull request like what changes you did.

Thanks
Satyam

**Comment by ShivanshPlays** [comment]
Okay, I'm on it thanks.

**Comment by ShivanshPlays** [comment]
Hi, I have forked and created a new branch but when I am running npm run dev it is asking for clerk and db setup, Do I have to set them up or is there a workaround? because the assigned issue is just for UI

**Comment by satyam8932** [comment]
Yeah you can setup them using your env variables which you can get from their official website

**Comment by ShivanshPlays** [comment]
okay got it

**Comment by ShivanshPlays** [comment]
Can you provide an  .env.example file so that I know what urls are needed for setting up the project??
I have provided a local postgres url but it is asking for clerk...It will be good too know what all URL are needed..

PS: bypassing is causing alot of issues so I am setting up properly

**Comment by satyam8932** [comment]
NEXT_BASE_URL
OPENAI_API_KEY
STRIPE_WEBHOOK_SIGNING_SECRET
NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
CLERK_SECRET_KEY
NEXT_PUBLIC_CLERK_SIGN_IN_URL
NEXT_PUBLIC_CLERK_SIGN_UP_URL
NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL
NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL
DATABASE_URL
NEXT_PUBLIC_FIREBASE_API_KEY
NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
NEXT_PUBLIC_FIREBASE_PROJECT_ID
NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
NEXT_PUBLIC_FIREBASE_APP_ID
NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID
FIREBASE_SERVICE_ACCOUNT_KEY
PINECONE_API_KEY
PINECONE_INDEX
STRIPE_API_KEY


These are all the variables which you need.

**Comment by satyam8932** [comment]
Due to no changes and PR's this issues is getting closed.
