### ISSUE TITLE
Header "GenieAI" overlapping with the navbar

### ISSUE THREAD

**Issue by Aditya6112** [satyam8932/genieai#20]
![Screenshot (245)](https://github.com/user-attachments/assets/e828551a-4c8d-491d-af22-0bc17f73488a)
For desktop version

![Screenshot (246)](https://github.com/user-attachments/assets/4672f42c-7b20-4603-834b-7792d3354a4d)

GenieAI that is barely visible in navbar you have to fix it for proper display sizes(media queries).

**Comment by Krishi1211** [comment]
You can go forward with this issue

**Comment by satyam8932** [comment]
@Aditya6112 I had already used TailwindCSS so you can also do the same for responsiveness, don't use raw CSS or any media queries that will make things cumbersome and hectic.

Thanks

**Comment by Aditya6112** [comment]
> @Aditya6112 I had already used TailwindCSS so you can also do the same for responsiveness, don't use raw CSS or any media queries that will make things cumbersome and hectic.
> 
> Thanks

Yes Thanks for sharing.

**Comment by iamsohelx** [comment]
Hii @satyam8932 can you please assign me this issue if Aditya is now working on it

**Comment by satyam8932** [comment]
@iamsohelx @Aditya6112 is already working on this issue so you can check for another one or can create a feature.

**Comment by iamsohelx** [comment]
Okay

**Comment by satyam8932** [comment]
Due to no changes or PRs this Issues has been closed.
