### ISSUE TITLE
The footer UI is not good 

### ISSUE THREAD

**Issue by jayanththalla** [satyam8932/genieai#21]
The footer is not better i want to make the changes in footer 
Please assign me @pa
![image](https://github.com/user-attachments/assets/56d7665a-45a0-462e-850a-90817f3e24bb)

**Comment by satyam8932** [comment]
hey, the footer is already in good condition you can find some other issues or bugs or may be you can implement a new AI tool as a feature for example the VoiceWiz ai tools is not implemented yet so you can add a new AI tool using OpenAI whisper or a model which user can use to chat through voice and for realtime communication u can use tRPC and other tools.
Try to do those things which gives you real world experience.

Good luck
