### ISSUE TITLE
Change Twitter Symbol to X in footer section

### ISSUE THREAD

**Issue by Amanjayswal500** [satyam8932/genieai#22]
I would like to propose a change to update the Twitter symbol to "X"  to reflect Twitter's recent rebranding. This change ensures consistency with the platform's new identity and avoids any potential confusion for users.
 please assign this issue to me
![Screenshot 2024-10-05 024206](https://github.com/user-attachments/assets/b29e7594-0699-4cac-a69d-47cd09f58243)

**Comment by satyam8932** [comment]
@Amanjayswal500 these are not a feature or bug fix try to find anything different which looks really an issue or a good feature that looks promising.
