### ISSUE TITLE
Addition of dark mode feature

### ISSUE THREAD

**Issue by unknown91tech** [satyam8932/genieai#23]
@satyam8932 I can add dark/light mode feature in your website. 

Can you assign this issue to me.

**Comment by satyam8932** [comment]
Ok sure go for it but please make sure that you don't break the existing functionality of the application and also write production grade code with proper comments.

Thanks

**Comment by unknown91tech** [comment]
@satyam8932 I am not able to set up all the env variables. Can you help me with that

**Comment by satyam8932** [comment]
NEXT_BASE_URL
OPENAI_API_KEY
STRIPE_WEBHOOK_SIGNING_SECRET
NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
CLERK_SECRET_KEY
NEXT_PUBLIC_CLERK_SIGN_IN_URL
NEXT_PUBLIC_CLERK_SIGN_UP_URL
NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL
NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL
DATABASE_URL
NEXT_PUBLIC_FIREBASE_API_KEY
NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
NEXT_PUBLIC_FIREBASE_PROJECT_ID
NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
NEXT_PUBLIC_FIREBASE_APP_ID
NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID
FIREBASE_SERVICE_ACCOUNT_KEY
PINECONE_API_KEY
PINECONE_INDEX
STRIPE_API_KEY

These are all the variables which you need.

**Comment by satyam8932** [comment]
You can go to each specific website and create accounts and use yours

**Comment by unknown91tech** [comment]
@satyam8932 I have made a pr for the feature. 
Can you review it once and tell me if any changes need to be made.

**Comment by Balamurugan-cyber** [comment]
please assign this issue

**Comment by satyam8932** [comment]
@Balamurugan-cyber  this issue is already been assigned to @unknown91tech
