### ISSUE TITLE
GSSOC EXT NOTICE: Improper Labeling in the Project

### ISSUE THREAD

**Issue by shreya-paul-17** [satyam8932/genieai#24]
Dear Project Admin @satyam8932 ,

It has come to our attention that your repository not applying the necessary labels to issues and merged PRs, which is affecting contributor scores on the leaderboard.

Please ensure you use the correct labels:

- gssoc-ext
- level1, level2, level3 
- hacktoberfest-accepted (only if your repository have Hacktoberfest topic in description)

*NOTE:* Level labels should not have any dashes between them. Spaces are allowed, but no dashes should be used.

Kindly review and update the labels on your issues and PRs to ensure fairness for all contributors. Failure to address this may result in your project being flagged.

Thank you,
Core Team
GSSoC '24 Extended

**Comment by satyam8932** [comment]
Hi @shreya-paul-17, Thanks for informing regarding the label issues. I appreciate your help and i have updated the lables according to your instructions.

Let me know if these are correct. By the way, no PRs have been merged till now.
So I have only added the lables on issues.

![image](https://github.com/user-attachments/assets/848a40c5-7058-4cd4-b510-96eca63321ea)

Thanks
Satyam

**Comment by shreya-paul-17** [comment]
Yes @satyam8932 these labels are ok
