### ISSUE TITLE
Dockerfile needs optimisation

### ISSUE THREAD

**Issue by PankajKumardev** [satyam8932/genieai#26]
"As I have seen in the Dockerfile, it is not optimized, and I believe it will have caching problems. I can optimize it."

add these labels too
GSSOC
hacktoberfest

**Comment by satyam8932** [comment]
@PankajKumardev , Thanks for your issue but currently, the application is not working with docker for now so no changes needed in docker.

You can try finding some other issues or features and implement them.

Thanks
