### ISSUE TITLE
Enhance Read Me File adding details and Contributors Image Badges section

### ISSUE THREAD

**Issue by Muskan-bhatt249** [satyam8932/genieai#28]
I can enhance the Read Me file and make it more attractive. I can add a section like this as the end showing Contributor Image badges
![Uploading Screenshot 2024-10-07 194813.png…]()

**Comment by satyam8932** [comment]
I'm not able to see the image @Muskan-bhatt249, can you please upload them properly?

**Comment by Muskan-bhatt249** [comment]
![Screenshot 2024-10-07 215924](https://github.com/user-attachments/assets/2277da9c-92e9-4fa5-a365-4484b627dc32)
@satyam8932 is it visible now?

**Comment by satyam8932** [comment]
ok sure @Muskan-bhatt249
