### ISSUE TITLE
Navbar conflicting 

### ISSUE THREAD

**Issue by PankajKumardev** [satyam8932/genieai#29]
In this image navbar is conflicting with GenieAI , i can fix this
![image](https://github.com/user-attachments/assets/977e5036-f7ba-4411-b8fc-d1c25c673018)

**Comment by satyam8932** [comment]
I don't think so may be there's a layout shift in your side due to browser as it's working fine by my side.

![image](https://github.com/user-attachments/assets/34a9a284-53c5-4387-aba6-4788c41efddb)


Please look for another issues or features.

**Comment by PankajKumardev** [comment]
i see , but i am facing this issue on my laptop , btw my laptop screen size 15.6inch
