### ISSUE TITLE
Adding the contributors page to mention all the awersome people who have contributed to the website.

### ISSUE THREAD

**Issue by tarunkumar2005** [satyam8932/genieai#33]
Adding the contributors page to mention all the awersome people who have contributed to the website.

@satyam8932 Assign this to me under gssoc 2024 ext and hacktoberfest i will work on this isssue.

**Comment by satyam8932** [comment]
This issue has already been fixed and completed.

**Comment by tarunkumar2005** [comment]
@satyam8932 i didn't saw any contributors page on the website that's why i raised the issue if you think that it is already done then its fine.
