### ISSUE TITLE
add contributing.md file

### ISSUE THREAD

**Issue by INam1995** [satyam8932/genieai#37]
Hey @satyam8932 
I would like to request to be assigned the issue for adding a CONTRIBUTING.md file to this Project. This file will provide clear guidelines for potential contributors, enhancing our community's onboarding experience and encouraging more participation.

Here’s a brief overview of what I plan to include in the CONTRIBUTING.md file:

Project Overview
Getting Started instructions
Contributing Guidelines
Implementation steps for the search functionality enhancement
Acknowledgment of the project's Code of Conduct

so please assign this issue to me under gssoc-ext

**Comment by satyam8932** [comment]
Project Overview and getting started things are already present in Readme.md and 
Contributing.md is not a feature bro so try to find some genuine issues.

Thanks
