### ISSUE TITLE
ADDING BACK TO TOP BUTTON AT THE LOWER SIDE OF THE SCREEN.

### ISSUE THREAD

**Issue by ABHISIKTAcommits** [satyam8932/genieai#39]
ENHANCING THE WEBSITE BY ADDING BACK TO TOP BUTTON AT THE LOWER SIDE OF THE SCREEN.
PLEASE ASSIGN THE ISSUE TO ME AND MARK AS HACKTOBERFEST-ACCEPTED, GSSOC-EXTD, AND LEVELS.

**Comment by satyam8932** [comment]
Hello @ABHISIKTAcommits thanks for your issue but that doesn't seems like a bug fix or a genuine feature.
Pelase try to find other bugs or features realted to AI development.

Thanks
