### ISSUE TITLE
ADDING THE "ABOUT US" SECTION.

### ISSUE THREAD

**Issue by ABHISIKTAcommits** [satyam8932/genieai#40]
A about us section needs to be added in the navbar or the page body for describing the work of the website.

PLEASE ASSIGN THE ISSUE TO ME AND MARK AS HACKTOBERFEST-ACCEPTED, GSSOC-EXTD, AND LEVELS.

**Comment by satyam8932** [comment]
No need of about section as the current application doesn't act as a blog
