### ISSUE TITLE
Request to add a CONTRIBUTING.md file

### ISSUE THREAD

**Issue by banasmita24** [satyam8932/genieai#43]
### Description
I noticed that the repository does not have a `CONTRIBUTING.md` file, which is essential for guiding new contributors on how to contribute effectively. Adding this file will help clarify the process for issues, pull requests, code standards, and other contribution guidelines.

### Suggested contents for `CONTRIBUTING.md`:
1. **Introduction**: Briefly describe the project and welcome contributors.
2. **How to Contribute**:
   - Reporting bugs.
   - Suggesting new features.
   - Pull request process.
   - Coding standards and best practices.
3. **Setting Up the Development Environment**:
   - Clone the repo.
   - Install dependencies.
   - Run the app/test.
4. **Commit Message Guidelines**: Structure for meaningful commit messages.
5. **Code of Conduct**: Optionally refer to or include a Code of Conduct.

### Benefits:
- It helps maintain consistency in contributions.
- Provides clarity for new contributors on how to start.
- Encourages more community involvement.

Please let me know if I can help with drafting this file.

Thank you :)

**Comment by satyam8932** [comment]
The working instructions are already provided in readme file.

Try to find something better.
