### ISSUE TITLE
ADD about us page to the website 

### ISSUE THREAD

**Issue by shubhagarwal1** [satyam8932/genieai#48]
The about us page will explain the motive of the website and also the info about the developers 
hey @satyam8932 please assign me this task

**Comment by kashvi9** [comment]
Hello @shubhagarwal1 
You can start working on this issue, but make sure to comment your code properly and attach proper screenshots. Happy Coding!

**Comment by satyam8932** [comment]
These pages are not needed as we are building an enterprise-grade application with full stream content that will make a direct impact, not like a blog page.
