### ISSUE TITLE
ADD a case studies page so that users can get educated about the product usage 

### ISSUE THREAD

**Issue by shubhagarwal1** [satyam8932/genieai#51]
refrence 
![Screenshot 2024-10-19 at 6 12 59 PM](https://github.com/user-attachments/assets/21bd8e8d-3643-4249-8d1d-b49b5441edde)

**Comment by satyam8932** [comment]
redundant and vague features

**Comment by shubhagarwal1** [comment]
hey @satyam8932 it would be a great opportunity for me to contribute to your repo
do you have anything specific that i can work.

**Comment by satyam8932** [comment]
Hi @shubhagarwal1 
Yes you can, like implement new enterprise grade AI tools or features that can ease users work, fix known bugs that are causing problems to run application on production server, etc.

But things like adding pages, fixing readme, and contributing files are not worth your time and will not give you anything to learn as they means no values as per the developer's perspective, so try to do some valuable and genuine contributions.

Best,
Satyam

**Comment by shubhagarwal1** [comment]
Can you suggest me any, jsut mention the thing and i will gracefully work on it.

**Comment by satyam8932** [comment]
try to add some ai tools like whisper models or in a way that users can communicate with ai models through Voice or making the image generating ai much better (ArtSynth), or something better ai models as our whole app is based on AI

**Comment by shubhagarwal1** [comment]
> Hi @shubhagarwal1 Yes you can, like implement new enterprise grade AI tools or features that can ease users work, fix known bugs that are causing problems to run application on production server, etc.
> 
> But things like adding pages, fixing readme, and contributing files are not worth your time and will not give you anything to learn as they means no values as per the developer's perspective, so try to do some valuable and genuine contributions.
> 
> Best, Satyam

@satyam8932, Understood about the contiributoios, can you help me with anyting specific you are planning to implement, woudl love to work on that.

**Comment by shubhagarwal1** [comment]
> try to add some ai tools like whisper models or in a way that users can communicate with ai models through Voice or making the image generating ai much better (ArtSynth), or something better ai models as our whole app is based on AI

understood, shoul di rename this issue or should i raise a new issue for the assignment of the task
