### ISSUE TITLE
Add Missing Meta Tags, sitemap, robots.txt for SEO Enhancement

### ISSUE THREAD

**Issue by myselfshivams** [satyam8932/genieai#53]
The current project lacks essential meta tags that are crucial for search engine optimization (SEO). To improve the visibility and ranking of the website on search engines, we need to add the following missing meta tags:

Title tags
Description tags
Keywords tags
Open Graph tags for social media sharing
Robots meta tag
@satyam8932  Please assign this issue to me (@myselfshivams).

Labels:

GSSoC
Hacktoberfest

**Comment by satyam8932** [comment]
this website is not indexed in any search engine so currently meta tags won't work for SEO.
