### ISSUE TITLE
Overlapping Text in Navigation Bar

### ISSUE THREAD

**Issue by AaryaShrivaastava** [satyam8932/genieai#62]
The website has a navigation bar rendering issue where the "GenieAI" title appears overlapped or duplicated. This could be due to CSS styling conflicts, particularly with TailwindCSS, or JavaScript issues affecting layout, which may arise from the Next.js framework or component libraries in TanStack. The overlapping text disrupts readability and affects the user experience, making it essential to address the styling and rendering of the navigation elements.

**Comment by AaryaShrivaastava** [comment]
please add the lables for GSSoC Extd

**Comment by satyam8932** [comment]
Unclear issues and tech stack stated with no images.
