### ISSUE TITLE
Navigation bar overlapping the homepage elements

### ISSUE THREAD

**Issue by AaryaShrivaastava** [satyam8932/genieai#63]
I understand that the previous issue raised did not have much clarity to it, hence I am raising the issue again with a video file so that it is easier to understand and work on it. 
The website has a navigation bar rendering issue where the "GenieAI" title appears to overlap. 
We can see in the video that the GenAI title element at the home page is overlapped by thee navigation bar.
The overlapping text disrupts readability and affects the user experience.

Hope it helps.
Please add gssoc extd label.
Thank you

https://github.com/user-attachments/assets/d5337c1b-0dfa-49e6-9e6e-6cfa07a45028

**Comment by satyam8932** [comment]
Thanks for writing a descriptive issue @AaryaShrivaastava  but I didn't see any issues. See the attached image.
![image](https://github.com/user-attachments/assets/a0cb4d06-d4c6-4012-b917-7ebaefdc6dbd)

**Comment by AaryaShrivaastava** [comment]
Thank you for letting me know. I visited the site again, and realised that when the website zoom is at 80%, the issue is not there, but at 100% zoom, that is the default zoom on browser, the issue prevails.

I request you to please have a look.
Thank you.

**Comment by satyam8932** [comment]
Hey thanks for letting me know but I that still there is no issues at 100% default zoom 

![image](https://github.com/user-attachments/assets/543b6974-dcbd-4930-9e2d-5c67f3adba28)


Thanks
