### ISSUE TITLE
Create Review Section at landing page

### ISSUE THREAD

**Issue by dev129** [satyam8932/genieai#64]
### Issue: Development of a Review Section
Hi @satyam8932 
#### **Objective**
Implement a Review section to capture and display user feedback on platform tools, features, and overall user experience. This section will serve as a valuable resource for potential users, helping them make informed decisions based on real user insights while fostering trust and transparency.

#### **Requirements**

1. **User Rating and Review Submission**:
   - Allow users to rate their experience on a scale (e.g., 1-5 stars).
   - Provide an input field for users to leave detailed comments about their experiences and specific tools they’ve used.

2. **Categorized Feedback**:
   - Organize reviews based on feature categories (e.g., **Coding Tools**, **YouTube SEO**, **Instagram Hashtag Generator**, **Writing Assistance**) to help new users easily find relevant feedback.

3. **Sorting and Filtering Options**:
   - Enable sorting by recent reviews, highest-rated, and lowest-rated, as well as filtering by specific tool categories for easier navigation.

4. **Highlighted Testimonials**:
   - Showcase standout reviews, such as those from verified users or industry professionals, to increase credibility and appeal.

5. **Review Moderation**:
   - Implement moderation tools to ensure the quality and relevance of displayed reviews, allowing for the removal of inappropriate or spam content.

6. **User Engagement**:
   - Allow users to upvote helpful reviews or mark reviews as helpful to increase engagement and assist other users in finding valuable feedback.

#### **Expected Benefits**

- **Increased User Trust**: A dedicated review section will demonstrate transparency and authenticity by highlighting actual user experiences.
- **Enhanced Product Development**: User feedback will provide actionable insights for refining and improving features.
- **Improved User Engagement**: Encouraging reviews creates an interactive community where users can share insights and discover tips from others.

This Review section will serve as a critical tool for collecting and displaying feedback, contributing to ongoing product improvements and fostering a more engaged, informed user community.

**Comment by satyam8932** [comment]
We are building an enterprise grade application which do no include these types of stated things. We are looking for features related to new AI models or any bug fixes.

Thanks
