### ISSUE TITLE
Navbar Redesign

### ISSUE THREAD

**Issue by dev129** [satyam8932/genieai#66]
Hi @satyam8932 
**Is your feature request related to a problem? Please describe.**  
Navigating through the site can sometimes feel cumbersome, especially on smaller screens. The current navbar lacks a streamlined design that adapts smoothly for both desktop and mobile users, making it difficult for users to access key sections quickly and intuitively.  

**Describe the solution you’d like**  
A redesigned, responsive navbar that includes a more intuitive layout and optimized accessibility. The navbar should incorporate clear links or icons for core sections, a dropdown for additional options, and possibly a search bar for easier navigation. On mobile, the navbar could collapse into a more compact form, such as a hamburger menu, that reveals key navigation links in an organized and user-friendly way.

**Describe alternatives you’ve considered**  
An alternative approach would be to keep the current navbar and add a sticky sidebar for secondary links. However, this might take up too much screen space on smaller devices and create a cluttered look.

**Additional context**  
Adding animation for smooth transitions, hover effects for desktop, and clearer iconography could significantly improve the navbar’s usability. Including the option to customize or expand sections based on user preferences would also enhance the navigation experience.

**Comment by satyam8932** [comment]
Please attach an image for what kind of issues you are facing with navbar then I can review that and think about it.

Thanks

**Comment by dev129** [comment]
![image](https://github.com/user-attachments/assets/89eba7cb-ac98-44cf-862d-297e9d4412e0)

This is the overall landing page , now if you see carefully, the title and navbar are overlapping each other which gives a bad look, secondly ther is no pricing, faw , use case, features.
Just think from the user's perspective, why shall that person sign up to your website , if he is only given a landing page with pricing section , which the user won't even notice on a mobile phone at first glance.

**Comment by dev129** [comment]
Hi @satyam8932 , are we still on ?

**Comment by satyam8932** [comment]
It's looking fine by my side; see the attached images:
![image](https://github.com/user-attachments/assets/1e66e6f4-4382-4bea-a599-eee1bbb35c0f)
