### ISSUE TITLE
📝[DOCS] adding Stargazers and Forkers section to readme.md

### ISSUE THREAD

**Issue by amiya-cyber** [satyam8932/genieai#68]
![2024-10-31](https://github.com/user-attachments/assets/fc792777-7a5b-4203-b1e9-b79fd7d3e174)

**Comment by kashvi9** [comment]
Hello @amiya-cyber 
Thank you for your initiative on this feature; however, it’s not required for our project at this time. I encourage you to explore other issues or enhancement opportunities that would align with our current priorities.
