### ISSUE TITLE
Adding Social Media Links to the Footer of README

### ISSUE THREAD

**Issue by amiya-cyber** [satyam8932/genieai#69]
This READ ME lacks a contact us section.
We can Add a visually appealing footer to the README that includes links to key social media profiles, making it easy for users to connect and stay updated. The footer should align with the project's branding, feature accessible icons (e.g., GitHub, Twitter, LinkedIn), and be mobile-friendly. Each link must be verified to open correctly, ideally in a new tab where possible. This enhancement will improve user engagement and provide quick access to our social platforms.

please assign and add level2 
![2024-11-01 (6)](https://github.com/user-attachments/assets/10ee37a9-82b7-405b-a66d-6cfdd19f8767)

**Comment by satyam8932** [comment]
Social pages are not build yet so no need for social things
